from selenium.webdriver.common.by import By

class Register:
    nameInput=(By.ID, "firstName")
    lastnameInput=(By.ID, "lastName")
    emailInput=(By.ID, "userEmail")
    passInput=(By.CSS_SELECTOR, "input[data-qa='login-password']")
    loginButton=(By.CSS_SELECTOR, "button[data-qa='login-button']")
    gender=(By.CSS_SELECTOR, "input[id='gender-radio-2']")
    mobileInput=(By.ID, "userNumber")
    birth=(By.ID, "dateOfBirthInput")
    month=(By.XPATH, "//select[@class='react-datepicker__month-select']/option[@value='9']")
    year=(By.XPATH, "//select[@class='react-datepicker__year-select']/option[@value='1995']")
    day=(By.XPATH, "//div[@class='react-datepicker__day react-datepicker__day--016']")
    subjectInput=(By.ID, "subjectsInput")
    optionSubject=(By.ID, "react-select-2-option-0")
    hobbie=(By.ID, "hobbies-checkbox-1")
    upload_file=(By.ID, "uploadPicture")
    inputState=(By.CSS_SELECTOR, "div[class='css-1wy0on6']")
    optionState=(By.ID, "react-select-3-option-0")
    footer=(By.ID, "submit")
    inputCity=(By.CSS_SELECTOR, "div[class='css-1xc3v61-indicatorContainer']")
    optionCity=(By.ID, "react-select-4-option-0")